rask: llm-sft
base_model: Qwen/Qwen3.5-0.8B
project_name: losie
log: tensorboard
backend: local

data:
  path: /data
  train_split: train
  valid_split: valid
  chat_template: tokenizer
  column_mapping:
    text_column: messages

params:
  block_size: 2048
  model_max_length: 4096
  epochs: 16
  batch_size: 128
  lr: 1e-5
  peft: true
  quantization: int4
  target_modules: all-linear
  padding: right
  optimizer: paged_adamw_8bit
  scheduler: linear
  gradient_accumulation: 8
  mixed_precision: bf16
  merge_adapter: true

hub:
  username: 
  token: 
  push_to_hub: false
